---
- name: Install Apache package
  package:
    name: "{{apache_pkg_name}}"
    state: present
    update_cache: yes

- name: Install mod_ssl
  yum:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - mod_ssl
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: Remvoe ssl.conf
  file:
    path: "{{apache_site_dir}}/{{item}}"
    state: absent
  with_items:
    - ssl.conf
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: Open the port 443
  iptables:
    chain: INPUT
    destination_port: 443
    action: insert
    jump: ACCEPT
    protocol: tcp
    state: present
  register: port_443_result
  when: common_iptables != 'disabled'

- name: Save iptables
  command: "/sbin/iptables-save"
  when: port_443_result is changed

- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: "{{apache_dir}}/"
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_apache.service

- name: Copy httpd.conf
  copy:
    src: "{{apache_pkg_name}}.conf"
    dest: "{{apache_conf_dir}}/"
    mode: 0644
  notify: Restart_apache.service

- name: Copy passwd file
  copy:
    src: "../../{{apache_rolename}}/files/{{apache_passwd_file}}"
    dest: "{{apache_dir}}/"
    mode: 0644
  when: apache_passwd_file|length > 0
  notify: Restart_apache.service

- name: Template of default.conf.j2
  template:
    src: default.conf.j2
    dest: "{{apache_site_dir}}/{{apache_server_name|default('000-default', true)}}.conf"
    mode: 0644
  vars:
    server_name: "{{apache_server_name}}"
    locations: "{{apache_locations}}"
    conf_dir: "{{apache_dir}}"
    mods_dir: "{{apache_modsdir}}"
    protected_location: "{{apache_protected_location}}"
    passwd_file: "{{apache_passwd_file}}"
    ldap_url: "{{apache_ldap_url}}"
    ldap_user: "{{apache_ldap_user}}"
    ldap_passwd: "{{apache_ldap_passwd|replace('\n', '')}}"
  notify: Restart_apache.service

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of apache.monit
  template:
    src: apache.monit.j2
    dest: "{{monit_includedir}}/apache.monit"
    mode: 0644
  vars:
    pidfile: "{{apache_pidfile}}"
    start_program: '/usr/bin/systemctl start {{apache_pkg_name}}'
    stop_program: '/usr/bin/systemctl stop {{apache_pkg_name}}'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
